version: "3.3"
services:
  db:
    image: postgres:12
    restart: unless-stopped
    container_name: local-db
    volumes:
      - app-db-data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: local-db

volumes:
  app-db-data: {}
