"""init

Revision ID: 345b50717705
Revises: 
Create Date: 2024-01-12 17:26:20.074736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345b50717705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id_answer', sa.BigInteger(), nullable=False),
    sa.Column('str_value', sa.String(), nullable=False),
    sa.Column('fk_question', sa.BigInteger(), nullable=False),
    sa.Column('fk_submission', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_answer')
    )
    op.create_index('answer_question_idx', 'answer', ['fk_question'], unique=False)
    op.create_index('answer_submission_idx', 'answer', ['fk_submission'], unique=False)
    op.create_table('form',
    sa.Column('id_form', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('instant_scoring', sa.Boolean(), nullable=True),
    sa.Column('show_wrong_answer', sa.Boolean(), nullable=True),
    sa.Column('show_correct_answer', sa.Boolean(), nullable=True),
    sa.Column('see_single_score', sa.Boolean(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=True),
    sa.Column('allow_resubmit', sa.Boolean(), nullable=True),
    sa.Column('show_progress', sa.Boolean(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('send_copy', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_form')
    )
    op.create_table('question',
    sa.Column('id_question', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('allow_multi', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_index('question_form_idx', 'question', ['fk_form'], unique=False)
    op.create_table('schedule',
    sa.Column('id_schedule', sa.BigInteger(), nullable=False),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('date_time', sa.BigInteger(), nullable=False),
    sa.Column('execution', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_schedule')
    )
    op.create_index('schedule_date_time_index', 'schedule', ['date_time'], unique=False)
    op.create_table('scheduled_email',
    sa.Column('id_schedule_email', sa.BigInteger(), nullable=False),
    sa.Column('fk_schedule', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_schedule_email')
    )
    op.create_index('scheduled_email_schedule_index', 'scheduled_email', ['fk_schedule'], unique=False)
    op.create_table('submission',
    sa.Column('id_submission', sa.BigInteger(), nullable=False),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_submission')
    )
    op.create_index('submission_form_idx', 'submission', ['fk_form'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('submission_form_idx', table_name='submission')
    op.drop_table('submission')
    op.drop_index('scheduled_email_schedule_index', table_name='scheduled_email')
    op.drop_table('scheduled_email')
    op.drop_index('schedule_date_time_index', table_name='schedule')
    op.drop_table('schedule')
    op.drop_index('question_form_idx', table_name='question')
    op.drop_table('question')
    op.drop_table('form')
    op.drop_index('answer_submission_idx', table_name='answer')
    op.drop_index('answer_question_idx', table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
